"""Witwin Core - Shared geometry, material, and structure contracts."""

__version__ = "0.4.0"

from .material import (
    DispersionSpec,
    FrequencyMaterialSample,
    MaterialCapabilities,
    MaterialLayer,
    MaterialSpec,
    PhaseScreen,
    PhysicalMaterial,
    PowerLawDispersion,
    StaticMaterialSample,
    SurfaceRoughness,
)
from .structure import (
    MaterialAssignment,
    Structure,
)
from .identity import (
    AntennaId,
    AssignmentId,
    MaterialId,
    PrimitiveId,
    StructureId,
    SurfaceId,
    new_antenna_id,
    new_assignment_id,
    new_material_id,
    new_structure_id,
    new_surface_id,
    reserve_antenna_id,
    reserve_assignment_id,
    reserve_material_id,
    reserve_structure_id,
    reserve_surface_id,
)
from .antenna import (
    AntennaPattern,
    AntennaState,
    ReceiverGrid,
    antenna_orientation_matrix,
)
from .scene import (
    EndpointState,
    Scene,
    SceneSnapshot,
    SceneVersions,
    StructureState,
)
from .dynamics import (
    Deformation,
    DeformationState,
    DynamicScene,
    LinearTrajectory,
    RigidMotion,
    Trajectory,
)
from .geometry import (
    Box,
    Cone,
    Cylinder,
    Ellipsoid,
    Geometry,
    GeometryBase,
    GeometrySpec,
    HollowBox,
    Mesh,
    Prism,
    Pyramid,
    Sphere,
    Torus,
)
from .math import (
    ComplexLike,
    ScalarLike,
    normalize_vec3,
    quat_from_euler,
    quat_identity,
    quat_multiply,
    quat_to_rotation_matrix,
    quat_to_rotation_matrix_np,
)
__all__ = [
    "GeometryBase",
    "GeometrySpec",
    "Box", "Sphere", "Cylinder", "Cone", "Ellipsoid",
    "Pyramid", "Prism", "Torus", "HollowBox",
    "AntennaId",
    "AntennaPattern",
    "AntennaState",
    "ReceiverGrid",
    "AssignmentId",
    "ComplexLike",
    "Deformation",
    "DeformationState",
    "DispersionSpec",
    "DynamicScene",
    "EndpointState",
    "MaterialAssignment",
    "MaterialCapabilities",
    "MaterialId",
    "MaterialLayer",
    "MaterialSpec",
    "Mesh",
    "FrequencyMaterialSample",
    "Geometry",
    "LinearTrajectory",
    "PhaseScreen",
    "PhysicalMaterial",
    "PowerLawDispersion",
    "PrimitiveId",
    "RigidMotion",
    "ScalarLike",
    "Scene",
    "SceneSnapshot",
    "SceneVersions",
    "StaticMaterialSample",
    "Structure",
    "StructureId",
    "SurfaceId",
    "StructureState",
    "SurfaceRoughness",
    "Trajectory",
    "antenna_orientation_matrix",
    "normalize_vec3",
    "new_antenna_id",
    "new_assignment_id",
    "new_material_id",
    "new_structure_id",
    "new_surface_id",
    "quat_from_euler",
    "quat_identity",
    "quat_multiply",
    "quat_to_rotation_matrix",
    "quat_to_rotation_matrix_np",
    "reserve_antenna_id",
    "reserve_assignment_id",
    "reserve_material_id",
    "reserve_structure_id",
    "reserve_surface_id",
]
